# The vLLM Dockerfile is used to construct vLLM image that can be directly used
# to run the OpenAI compatible server.

FROM ubuntu:22.04 AS dev

RUN apt-get update -y && \
    apt-get install -y \
        git python3-pip \
        ffmpeg libsm6 libxext6 libgl1
WORKDIR /workspace

COPY . /workspace/vllm

# build vLLM with OpenVINO backend
RUN --mount=type=cache,target=/root/.cache/pip \
    PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"
    VLLM_TARGET_DEVICE="openvino" \
    python3 -m pip install -v /workspace/vllm/

CMD ["/bin/bash"]
