# In this file, you can add more tests to run either by adding a new step or
# adding a new command to an existing step. See different options here for examples.
# This script will be feed into Jinja template in `test-template-aws.j2` to generate
# the final pipeline yaml file.

steps:
- label: Regression Test
  mirror_hardwares: [amd]
  command: pytest -v -s test_regression.py
  working_dir: "/vllm-workspace/tests" # optional

- label: Multi-node Tests
  num_gpus: 4
  multi_node: True
  commands:
    node0: VLLM_TEST_SAME_HOST=0 torchrun --nproc-per-node=2 --nnodes 2 --rdzv_backend=c10d --rdzv_endpoint=192.168.10.10 tests/distributed/test_same_node.py
    node1: VLLM_TEST_SAME_HOST=0 torchrun --nproc-per-node=2 --nnodes 2 --rdzv_backend=c10d --rdzv_endpoint=192.168.10.11 tests/distributed/test_same_node.py
