# In this file, you can add more tests to run either by adding a new step or
# adding a new command to an existing step. See different options here for examples.
# This script will be feed into Jinja template in `test-template.j2` to generate
# the final pipeline yaml file.

steps:
- label: Versioning
  command: python collect_env.py
- label: Speculative decoding tests
  #mirror_hardwares: [amd]
  working_dir: "/vllm-workspace/tests/spec_decode/e2e"
  command: pytest -vv -s test_multistep_correctness.py
