# In this file, you can add more tests to run either by adding a new step or
# adding a new command to an existing step. See different options here for examples.
# This script will be feed into Jinja template in `test-template.j2` to generate
# the final pipeline yaml file.

steps:
- label: LoRA Test %N
  #mirror_hardwares: [amd]
  command: pytest -v -s lora --shard-id=$$BUILDKITE_PARALLEL_JOB --num-shards=$$BUILDKITE_PARALLEL_JOB_COUNT --ignore=lora/test_long_context.py
  parallelism: 4

- label: LoRA Long Context (Distributed)
  #mirror_hardwares: [amd]
  num_gpus: 4
  # This test runs llama 13B, so it is required to run on 4 GPUs.
  commands:
    # Temporarily run this way because we cannot clean up GPU mem usage
    # for multi GPU tests.
    # TODO(sang): Fix it.
    - pytest -v -s lora/test_long_context.py::test_rotary_emb_replaced
    - pytest -v -s lora/test_long_context.py::test_batched_rope_kernel
    - pytest -v -s lora/test_long_context.py::test_self_consistency
    - pytest -v -s lora/test_long_context.py::test_quality
    - pytest -v -s lora/test_long_context.py::test_max_len

- label: Metrics Test
  mirror_hardwares: [amd]
  command: pytest -v -s metrics
