steps:
  - label: "Wait for container to be ready"
    agents:
      queue: A100
    plugins:
    - kubernetes:
        podSpec:
          containers:
          - image: badouralix/curl-jq
            command:
            - sh .buildkite/nightly-benchmarks/scripts/wait-for-image.sh

  - wait
  
  - label: "A100"
    agents:
      queue: A100
    env:
      GPU: "A100"
      VLLM_USAGE_SOURCE: "ci-test"
      CMD: "bash .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh"
    commands:
      - pip install -U modal
      - modal token set --token-id "$(buildkite-agent secret get modal_token_id)" --token-secret "$(buildkite-agent secret get modal_token_secret)"
      - export HF_TOKEN="$(buildkite-agent secret get hf_token_secret)"
      - modal run .buildkite/nightly-benchmarks/scripts/launch-modal-runner.py

  - label: "H200"
    # skip: "use this flag to conditionally skip the benchmark step, useful for PR testing"
    agents:
      queue: H200
    plugins:
    - docker#v5.12.0:
        image: public.ecr.aws/q9t5s3a7/vllm-ci-postmerge-repo:$BUILDKITE_COMMIT
        command:
        - bash
        - .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh
        mount-buildkite-agent: true
        propagate-environment: true
        ipc: host
        gpus: 4,5,6,7
        volumes:
          - /data/benchmark-hf-cache:/root/.cache/huggingface
        environment:
        - VLLM_USAGE_SOURCE
        - HF_TOKEN

  - block: "Run H100 Benchmark"
    key: block-h100
    depends_on: ~

  - label: "H100"
    agents:
      queue: H100
    depends_on: block-h100
    env:
      GPU: "H100"
      VLLM_USAGE_SOURCE: "ci-test"
      CMD: "bash .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh"
    commands:
      - pip install -U modal
      - modal token set --token-id "$(buildkite-agent secret get modal_token_id)" --token-secret "$(buildkite-agent secret get modal_token_secret)"
      - export HF_TOKEN="$(buildkite-agent secret get hf_token_secret)"
      - modal run .buildkite/nightly-benchmarks/scripts/launch-modal-runner.py