name: Lint documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v19.0.0
        with:
          globs: '**/*.md'
